/** CRM import field definitions with labels and header aliases for auto-mapping */

/**
 * Cold / Warm / Qualified lead CSV mapping — aligns with Create Cold Lead form
 * and mirrors contact import options where the lead API supports the same data.
 */
export const LEAD_IMPORT_FIELDS = [
  { key: 'owner_id', label: 'Lead Owner', aliases: ['owner', 'owner_id', 'owner_email', 'lead_owner', 'contact_owner'] },
  { key: 'salutation', label: 'Salutation', aliases: ['prefix', 'honorific'] },
  { key: 'first_name', label: 'First Name', required: true, aliases: ['firstname', 'first', 'givenname', 'given_name', 'fname'] },
  { key: 'last_name', label: 'Last Name', required: true, aliases: ['lastname', 'last', 'surname', 'familyname', 'lname'] },
  { key: 'company', label: 'Company', required: true, aliases: ['organization', 'organisation', 'org', 'account', 'companyname', 'account_name', 'company_name', 'accountname'] },
  { key: 'email', label: 'Email', required: true, aliases: ['emailaddress', 'email_address', 'mail', 'e_mail'] },
  { key: 'phone', label: 'Phone', aliases: ['phonenumber', 'phone_number', 'telephone', 'tel', 'workphone', 'work_phone'] },
  { key: 'mobile', label: 'Mobile', aliases: ['mobilephone', 'mobile_phone', 'cell', 'cellphone'] },
  { key: 'fax', label: 'Fax', aliases: ['faxnumber', 'fax_number'] },
  { key: 'title', label: 'Title / Designation', aliases: ['designation', 'jobtitle', 'job_title', 'role', 'position'] },
  { key: 'lead_source', label: 'Lead Source', aliases: ['source', 'leadsource'] },
  { key: 'lead_status', label: 'Lead Status', aliases: ['status', 'lead_status', 'lead status'] },
  { key: 'lost_reason', label: 'Lost Reason', aliases: ['lostreason', 'loss_reason'] },
  { key: 'campaign_name', label: 'Campaign', aliases: ['campaign', 'campaign_id', 'campaign name'] },
  { key: 'industry', label: 'Industry', aliases: ['industry_type', 'sector', 'vertical'] },
  { key: 'website', label: 'Website', aliases: ['web', 'url', 'homepage', 'site'] },
  { key: 'annual_revenue', label: 'Annual Revenue', aliases: ['revenue', 'annualrevenue'] },
  { key: 'no_of_employees', label: 'No. of Employees', aliases: ['employees', 'employee_count', 'headcount', 'number_of_employees'] },
  { key: 'rating', label: 'Rating', aliases: ['lead_rating'] },
  { key: 'email_opt_out', label: 'Email Opt Out', aliases: ['opt_out', 'emailoptout', 'do_not_email'] },
  { key: 'skype_id', label: 'LinkedIn', aliases: ['linkedin', 'linkedin_url', 'linkedin_profile', 'linkedin url', 'li_url', 'profile_url', 'skype'] },
  { key: 'secondary_email', label: 'Secondary Email', aliases: ['alt_email', 'alternate_email', 'email2'] },
  { key: 'twitter', label: 'Twitter', aliases: ['twitter_handle', 'x', 'x_handle'] },
  { key: 'building', label: 'Flat / Building', aliases: ['mailing_flat', 'mailing_building', 'mailing_apartment', 'flat'] },
  { key: 'street', label: 'Street', aliases: ['mailing_street', 'address', 'mailing_address', 'address1'] },
  { key: 'city', label: 'City', aliases: ['mailing_city', 'mailingcity'] },
  { key: 'state', label: 'State / Province', aliases: ['mailing_state', 'province'] },
  { key: 'country', label: 'Country', aliases: ['mailing_country'] },
  { key: 'zip_code', label: 'Zip / Postal Code', aliases: ['zip', 'postal', 'zipcode', 'mailing_zip', 'mailing_zip_code', 'mailing_postal'] },
  { key: 'latitude', label: 'Latitude', aliases: ['mailing_lat', 'lat'] },
  { key: 'longitude', label: 'Longitude', aliases: ['mailing_lng', 'lng', 'lon'] },
  { key: 'description', label: 'Description', aliases: ['notes', 'comment', 'comments', 'keywords'] },
];

/** Matches fields on the Create Contact form */
export const CONTACT_IMPORT_FIELDS = [
  { key: 'owner_id', label: 'Contact Owner', aliases: ['owner', 'owner_id', 'owner_email', 'contact_owner'] },
  { key: 'salutation', label: 'Salutation', aliases: ['prefix', 'honorific'] },
  { key: 'first_name', label: 'First Name', required: true, aliases: ['firstname', 'first', 'givenname', 'fname'] },
  { key: 'last_name', label: 'Last Name', required: true, aliases: ['lastname', 'last', 'surname', 'lname'] },
  { key: 'email', label: 'Email', required: true, aliases: ['emailaddress', 'email_address', 'mail'] },
  { key: 'account_name', label: 'Company Name', required: true, aliases: ['account', 'company', 'organization', 'accountname', 'company_name', 'companyname'] },
  { key: 'phone', label: 'Phone', aliases: ['phonenumber', 'phone_number', 'telephone', 'tel'] },
  { key: 'other_phone', label: 'Other Phone', aliases: ['otherphone', 'alt_phone', 'alternate_phone'] },
  { key: 'mobile', label: 'Mobile', aliases: ['mobilephone', 'cell', 'cellphone', 'mobile_phone'] },
  { key: 'home_phone', label: 'Home Phone', aliases: ['homephone', 'home'] },
  { key: 'fax', label: 'Fax', aliases: ['faxnumber', 'fax_number'] },
  { key: 'assistant', label: 'Assistant', aliases: ['asst', 'pa'] },
  { key: 'asst_phone', label: 'Asst Phone', aliases: ['assistant_phone', 'asstphone'] },
  { key: 'lead_source', label: 'Lead Source', aliases: ['source', 'leadsource'] },
  { key: 'lead_status', label: 'Lead Status', aliases: ['status', 'lead_status', 'lead status'] },
  { key: 'campaign_name', label: 'Campaign', aliases: ['campaign', 'campaign_id', 'campaign name'] },
  { key: 'title', label: 'Designation', aliases: ['designation', 'jobtitle', 'job_title', 'role', 'position'] },
  { key: 'department', label: 'Department', aliases: ['dept'] },
  { key: 'industry', label: 'Industry', aliases: ['industry_type', 'sector', 'vertical'] },
  { key: 'date_of_birth', label: 'Date of Birth', aliases: ['dob', 'birthday', 'birth_date', 'dateofbirth'] },
  { key: 'email_opt_out', label: 'Email Opt Out', aliases: ['opt_out', 'emailoptout', 'do_not_email'] },
  { key: 'skype_id', label: 'LinkedIn', aliases: ['linkedin', 'linkedin_url', 'linkedin_profile', 'linkedin url', 'li_url', 'profile_url', 'skype'] },
  { key: 'secondary_email', label: 'Secondary Email', aliases: ['alt_email', 'alternate_email', 'email2'] },
  { key: 'twitter', label: 'Twitter', aliases: ['twitter_handle', 'x', 'x_handle'] },
  { key: 'website', label: 'Website', aliases: ['web', 'url', 'homepage', 'site'] },
  { key: 'mailing_flat', label: 'Mailing Flat / Building', aliases: ['mailing_building', 'mailing_apartment'] },
  { key: 'mailing_street', label: 'Mailing Street', aliases: ['street', 'address', 'mailing_address', 'address1'] },
  { key: 'mailing_city', label: 'Mailing City', aliases: ['city', 'mailingcity'] },
  { key: 'mailing_state', label: 'Mailing State / Province', aliases: ['state', 'province', 'mailing_state'] },
  { key: 'mailing_country', label: 'Mailing Country', aliases: ['country', 'mailing_country'] },
  { key: 'mailing_zip', label: 'Mailing Zip / Postal Code', aliases: ['zip', 'postal', 'zipcode', 'mailing_zip_code', 'mailing_postal'] },
  { key: 'mailing_lat', label: 'Mailing Latitude', aliases: ['latitude', 'lat'] },
  { key: 'mailing_lng', label: 'Mailing Longitude', aliases: ['longitude', 'lng', 'lon'] },
  { key: 'other_flat', label: 'Other Flat / Building', aliases: ['other_building'] },
  { key: 'other_street', label: 'Other Street', aliases: ['other_address'] },
  { key: 'other_city', label: 'Other City', aliases: [] },
  { key: 'other_state', label: 'Other State / Province', aliases: [] },
  { key: 'other_country', label: 'Other Country', aliases: [] },
  { key: 'other_zip', label: 'Other Zip / Postal Code', aliases: ['other_postal', 'other_zip_code'] },
  { key: 'other_lat', label: 'Other Latitude', aliases: [] },
  { key: 'other_lng', label: 'Other Longitude', aliases: [] },
  { key: 'description', label: 'Description', aliases: ['notes', 'comment', 'comments'] },
];

export function getImportFields(module) {
  if (module === 'contacts') return CONTACT_IMPORT_FIELDS;
  return LEAD_IMPORT_FIELDS;
}
